export const usStates = [
  {
    id: 1,
    value: "AL",
    label: "Alabama",
    timeZone: {
      standard: "UTC-06:00",
      dst: "UTC-05:00",
    },
    cities: ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
  },
  {
    id: 2,
    value: "AK",
    label: "Alaska",
    timeZone: [
      { region: "Most", standard: "UTC-09:00", dst: "UTC-08:00" },
      { region: "Adak", standard: "UTC-10:00", dst: "UTC-09:00" },
      { region: "Metlakatla", standard: "UTC-08:00", dst: null },
    ],
    cities: ["Anchorage", "Juneau", "Fairbanks", "Sitka", "Ketchikan"],
  },
  {
    id: 3,
    value: "AZ",
    label: "Arizona",
    timeZone: [{ region: "Most", standard: "UTC-07:00", dst: null }],
    cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Glendale"],
  },
  {
    id: 4,
    value: "AR",
    label: "Arkansas",
    timeZone: [{ region: "Most", standard: "UTC-06:00", dst: "UTC-05:00" }],
    cities: [
      "Little Rock",
      "Fort Smith",
      "Fayetteville",
      "Springdale",
      "Jonesboro",
    ],
  },
  {
    id: 5,
    value: "CA",
    label: "California",
    timeZone: [{ region: "Most", standard: "UTC-08:00", dst: "UTC-07:00" }],
    cities: [
      "Los Angeles",
      "San Francisco",
      "San Diego",
      "Sacramento",
      "Fresno",
    ],
  },

  {
    id: 6,
    value: "CO",
    label: "Colorado",
    timeZone: [{ region: "Most", standard: "UTC-07:00", dst: "UTC-06:00" }],
    cities: ["Denver", "Colorado Springs", "Aurora", "Boulder", "Fort Collins"],
  },
  {
    id: 7,
    value: "CT",
    label: "Connecticut",
    timeZone: [{ region: "Most", standard: "UTC-05:00", dst: "UTC-04:00" }],
    cities: ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury"],
  },

  {
    id: 8,
    value: "DE",
    label: "Delaware",
    timeZone: [{ region: "Most", standard: "UTC-05:00", dst: "UTC-04:00" }],
    cities: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
  },

  {
    id: 10,
    value: "FL",
    label: "Florida",
    timeZone: [
      { region: "Most", standard: "UTC-05:00", dst: "UTC-04:00" },
      { region: "Panhandle", standard: "UTC-06:00", dst: "UTC-05:00" },
    ],
    cities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee"],
  },

  {
    id: 11,
    value: "GA",
    label: "Georgia",
    timeZone: [{ region: "Most", standard: "UTC-05:00", dst: "UTC-04:00" }],
    cities: ["Atlanta", "Savannah", "Augusta", "Macon", "Columbus"],
  },

  {
    id: 12,
    value: "HI",
    label: "Hawaii",
    timeZone: [{ region: "Hawaii-Aleutian", standard: "UTC-10:00", dst: null }],
    cities: ["Honolulu", "Hilo", "Kailua", "Pearl City", "Kapolei"],
  },

  {
    id: 13,
    value: "ID",
    label: "Idaho",
    timeZone: [
      { region: "Pacific", standard: "UTC-08:00", dst: "UTC-07:00" },
      { region: "Mountain", standard: "UTC-07:00", dst: "UTC-06:00" },
    ],
    cities: ["Boise", "Nampa", "Meridian", "Idaho Falls", "Pocatello"],
  },
  {
    id: 14,
    value: "IL",
    label: "Illinois",
    timeZone: [{ region: "Central", standard: "UTC-06:00", dst: "UTC-05:00" }],
    cities: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford"],
  },
  {
    id: 15,
    value: "IN",
    label: "Indiana",
    timeZone: [
      { region: "Eastern", standard: "UTC-05:00", dst: "UTC-04:00" },
      { region: "Central", standard: "UTC-06:00", dst: "UTC-05:00" },
    ],
    cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Gary"],
  },
  {
    id: 16,
    value: "IA",
    label: "Iowa",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: [
      "Des Moines",
      "Cedar Rapids",
      "Davenport",
      "Sioux City",
      "Iowa City",
    ],
  },
  {
    id: 17,
    value: "KS",
    label: "Kansas",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Topeka", "Wichita", "Kansas City", "Olathe", "Overland Park"],
  },
  {
    id: 18,
    value: "KY",
    label: "Kentucky",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Louisville",
      "Lexington",
      "Bowling Green",
      "Covington",
      "Owensboro",
    ],
  },
  {
    id: 19,
    value: "LA",
    label: "Louisiana",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: [
      "New Orleans",
      "Baton Rouge",
      "Shreveport",
      "Lafayette",
      "Lake Charles",
    ],
  },
  {
    id: 20,
    value: "ME",
    label: "Maine",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Portland", "Augusta", "Bangor", "Lewiston", "Auburn"],
  },
  {
    id: 21,
    value: "MD",
    label: "Maryland",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Baltimore",
      "Columbia",
      "Silver Spring",
      "Frederick",
      "Rockville",
    ],
  },
  {
    id: 22,
    value: "MA",
    label: "Massachusetts",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"],
  },
  {
    id: 23,
    value: "MI",
    label: "Michigan",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Detroit", "Grand Rapids", "Flint", "Ann Arbor", "Lansing"],
  },
  {
    id: 24,
    value: "MN",
    label: "Minnesota",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"],
  },
  {
    id: 25,
    value: "MS",
    label: "Mississippi",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Jackson", "Gulfport", "Biloxi", "Hattiesburg", "Southaven"],
  },
  {
    id: 26,
    value: "MO",
    label: "Missouri",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: [
      "St. Louis",
      "Kansas City",
      "Columbia",
      "Springfield",
      "Independence",
    ],
  },
  {
    id: 27,
    value: "MT",
    label: "Montana",
    timeZone: { standard: "UTC-07:00", dst: "UTC-06:00" },
    cities: ["Billings", "Missoula", "Bozeman", "Helena", "Great Falls"],
  },
  {
    id: 28,
    value: "NE",
    label: "Nebraska",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
  },
  {
    id: 29,
    value: "NV",
    label: "Nevada",
    timeZone: { standard: "UTC-08:00", dst: "UTC-07:00" },
    cities: ["Las Vegas", "Reno", "Henderson", "Carson City", "Sparks"],
  },
  {
    id: 30,
    value: "NH",
    label: "New Hampshire",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Manchester", "Nashua", "Concord", "Derry", "Keene"],
  },
  {
    id: 31,
    value: "NJ",
    label: "New Jersey",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison"],
  },
  {
    id: 32,
    value: "NM",
    label: "New Mexico",
    timeZone: { standard: "UTC-07:00", dst: "UTC-06:00" },
    cities: ["Albuquerque", "Santa Fe", "Las Cruces", "Roswell", "Rio Rancho"],
  },
  {
    id: 33,
    value: "NY",
    label: "New York",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["New York City", "Buffalo", "Rochester", "Syracuse", "Albany"],
  },
  {
    id: 34,
    value: "NC",
    label: "North Carolina",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"],
  },
  {
    id: 35,
    value: "ND",
    label: "North Dakota",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
  },
  {
    id: 36,
    value: "OH",
    label: "Ohio",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"],
  },
  {
    id: 37,
    value: "OK",
    label: "Oklahoma",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
  },
  {
    id: 38,
    value: "OR",
    label: "Oregon",
    timeZone: { standard: "UTC-08:00", dst: "UTC-07:00" },
    cities: ["Portland", "Salem", "Eugene", "Gresham", "Beaverton"],
  },
  {
    id: 39,
    value: "PA",
    label: "Pennsylvania",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"],
  },
  {
    id: 40,
    value: "RI",
    label: "Rhode Island",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Providence",
      "Warwick",
      "Cranston",
      "Pawtucket",
      "East Providence",
    ],
  },
  {
    id: 41,
    value: "SC",
    label: "South Carolina",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Columbia",
      "Charleston",
      "Greenville",
      "Spartanburg",
      "Myrtle Beach",
    ],
  },
  {
    id: 42,
    value: "SD",
    label: "South Dakota",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
  },
  {
    id: 43,
    value: "TN",
    label: "Tennessee",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"],
  },
  {
    id: 44,
    value: "TX",
    label: "Texas",
    timeZone: [
      { region: "Central", standard: "UTC-06:00", dst: "UTC-05:00" },
      { region: "Mountain", standard: "UTC-07:00", dst: "UTC-06:00" },
    ],
    cities: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
  },
  {
    id: 45,
    value: "UT",
    label: "Utah",
    timeZone: { standard: "UTC-07:00", dst: "UTC-06:00" },
    cities: ["Salt Lake City", "Provo", "West Jordan", "Orem", "Sandy"],
  },
  {
    id: 46,
    value: "VT",
    label: "Vermont",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Burlington",
      "Essex",
      "South Burlington",
      "Colchester",
      "Bennington",
    ],
  },
  {
    id: 47,
    value: "VA",
    label: "Virginia",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Virginia Beach",
      "Norfolk",
      "Chesapeake",
      "Richmond",
      "Newport News",
    ],
  },
  {
    id: 48,
    value: "WA",
    label: "Washington",
    timeZone: { standard: "UTC-08:00", dst: "UTC-07:00" },
    cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"],
  },
  {
    id: 49,
    value: "WV",
    label: "West Virginia",
    timeZone: { standard: "UTC-05:00", dst: "UTC-04:00" },
    cities: [
      "Charleston",
      "Huntington",
      "Morgantown",
      "Parkersburg",
      "Wheeling",
    ],
  },
  {
    id: 50,
    value: "WI",
    label: "Wisconsin",
    timeZone: { standard: "UTC-06:00", dst: "UTC-05:00" },
    cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
  },
  {
    id: 51,
    value: "WY",
    label: "Wyoming",
    timeZone: { standard: "UTC-07:00", dst: "UTC-06:00" },
    cities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"],
  },
];
